name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools openjdk-8-jdk zip unzip
        pip3 install --upgrade pip
        pip3 install cython buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AliPredictionTool-apk
        path: bin/*.apk
